# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
    - pylint -E --disable=E0611,E0401 app/

pytest:
  stage: Test
  script:
    - cd test
     - pytest -v